const services = [
    {name: "Post-op Massages", description: "Post op lymphatic drainage massages promote healing, reduce swelling after surgery. These gentle massages stimulate lymphatic system, eliminate excess fluids and toxins. They accelerate healing, enhance immunity, alleviate discomfort. Therapists use precise movements to target areas, ensuring optimal results, minimizing complications. These massages enhance well-being, restore balance, offering a soothing solution for a faster recovery.", img: "./img/1.png"},
    {name: "Body slimming and sculpting massages", description: "Contour and shape the body using techniques like deep tissue manipulation, kneading, and lymphatic drainage. They target specific areas, stimulate circulation, break down fat deposits, and tone muscles, reducing cellulite and tightening skin. Therapists customize sessions for individual needs, providing a rejuvenating experience. With their ability to promote inch loss, improve skin texture, and enhance body confidence, these massages offer a non-invasive approach to achieving a slimmer physique.", img: "./img/2.png"},
    {name: "Fibrosis Treatment", description: "Fibrosis treatment after liposuction involves manual techniques like deep tissue massage, myofascial release, and lymphatic drainage. These methods break down scar tissue and adhesions, promoting proper healing. By softening and smoothing affected areas, it improves comfort and aesthetic outcomes, aiding in a quicker recovery.", img: "./img/3.png"},
    {name: "Cellulite Treatment", description: "Indulge in our spa's exceptional cellulite treatments, designed to help you achieve smoother, toned skin. Our expert therapists employ advanced massage techniques, innovative laser and radiofrequency therapies, and provide holistic wellness advice. Experience remarkable results as we target cellulite, boost collagen production, and enhance your natural contours. Join our community of satisfied clients and schedule a consultation today to embark on your journey towards cellulite-free confidence.", img: "./img/4.png"},
    {name: "Buttlifting", description: "Discover the transformative power of our exclusive buttlifting treatments at our spa. Our skilled therapists utilize advanced techniques to sculpt and tone your glutes, enhancing their shape and firmness. Experience a lifted and more defined backside with our proven buttlifting treatments.", img: "./img/5.png"},
    {name: "Arm Reduction Massages", description: "Achieve beautifully sculpted arms with our specialized arm reduction massages. Our skilled therapists use targeted techniques to tone and tighten the arms, reducing unwanted flabbiness and promoting a more defined appearance. Experience the confidence of sleek and slender arms.", img: "./img/6.png"},
    {name: "Chin Reduction", description: "Experience the remarkable effects of our chin reduction massages at our spa. Our skilled therapists utilize specialized techniques to target and tone the chin area, reducing excess fat and promoting a more defined jawline. Discover the confidence of a sleeker, more sculpted chin.", img: "./img/7.png"},
    {name: "Carboxy Therapy", description: "Carboxy therapy is a powerful treatment to slim, tone, reduce stretch marks, and break down fat. By injecting medical-grade carbon dioxide gas, it boosts blood flow, improves oxygenation, and stimulates collagen production. This results in enhanced skin elasticity, reduced cellulite, and smoother texture. Experience the transformative benefits of carboxy therapy for a more sculpted and rejuvenated appearance.", img: "./img/carbox.png"},
    {name: "Meso therapy", description: "A breakthrough treatment designed to effectively break down stubborn fat deposits. Through the use of specialized injections containing a combination of fat-dissolving substances and natural extracts, it targets localized areas and promotes fat metabolism. This non-surgical procedure helps to reshape and contour the body, resulting in a more sculpted and toned appearance. Experience the transformative power of meso therapy and say goodbye to stubborn fat.", img: "./img/meso.png"},
    {name: "Massages", description: `Relaxing Massages: Indulge in our soothing massages:
    Prenatal: Experience gentle relaxation and relief for expectant mothers, promoting overall well-being and reducing pregnancy discomfort.
    Swedish: Immerse yourself in a blissful journey of relaxation with long, flowing strokes that alleviate stress, enhance circulation, and restore balance.
    Deep Tissue: Delve into deep muscular release as our therapists use targeted techniques to alleviate tension, ease muscle knots, and promote a renewed sense of well-being.`, img: "./img/massages.png"},
    {name: "Ink- Permanent Make up", description: "Enhance your natural beauty with our impeccable permanent makeup services. Our skilled artists specialize in a range of treatments, including eyebrow enhancements, lip blushing, and eye liner, all meticulously crafted to bring out your best features. Wake up every day with flawlessly defined eyebrows, perfectly tinted lips, and mesmerizing eye accents. With our expert techniques and premium quality pigments, we ensure long-lasting results that will leave you feeling confident and beautiful. Embrace the convenience and beauty of permanent makeup, meticulously tailored to your unique style. Schedule your appointment today and let our talented artists create a look that will enhance your natural radiance.", img: "./img/ink.png"},
    {name: "Facials", description: `Immerse yourself in the world of rejuvenation with our extensive range of indulgent facials. Our spa offers a wide variety of treatments tailored to meet your specific skincare needs.
    Experience the luxury of our hydrating facials, designed to replenish and restore moisture for a radiant complexion. Treat yourself to our deep cleansing facials, which unclog pores, remove impurities, and leave your skin refreshed and revitalized.
    Discover the transformative effects of our anti-aging facials, featuring advanced techniques and potent ingredients to reduce fine lines, wrinkles, and promote youthful-looking skin. Rejuvenate your skin with our brightening facials, targeting hyperpigmentation and uneven skin tone, for a luminous and even complexion.
    For those seeking a holistic approach, our organic facials use natural, eco-friendly products to purify, nourish, and renew your skin, leaving you feeling refreshed and renewed.
    Indulge in the ultimate pampering with our spa signature facials, carefully curated to provide a unique and personalized experience, tailored to your skin's specific needs and preferences.
    With the expertise of our skilled estheticians and the finest quality products, our facials deliver unparalleled results. Treat yourself to a blissful journey of relaxation and rejuvenation. Book your facial appointment today and experience the true essence of radiant, glowing skin.`, img: "./img/facials.png"},
    {name: "Vag-acials, Back-acials, and Butt-acials!", description: "Gone are the days when facials were solely for your face. At Dazzling Spa, we believe in providing holistic care for your entire body. Our specialized treatments target specific areas, such as the delicate vaginal area, back, and buttocks, to promote rejuvenation, purification, and ultimate radiance. Experience the transformative power of our expert therapists who utilize advanced techniques and premium products to deliver exceptional results. Pamper yourself with our unique and comprehensive range of services, and discover a new level of beauty and confidence. Indulge in the extraordinary—because you deserve it.", img: "./img/bodyfacials.png"},
    {name: "VI peel", description: "Experience the transformative power of the VI Peel, our medical-grade peel at our spa. This advanced treatment delivers dramatic results, addressing a range of skin concerns. From acne scars to fine lines, hyperpigmentation to uneven texture, the VI Peel rejuvenates and revitalizes your complexion. With minimal downtime, you'll enjoy smoother, more radiant skin. Trust our skilled professionals to perform this safe and effective procedure. Unveil a more youthful, vibrant you. Schedule your VI Peel appointment today and embark on your journey to glowing skin.", img: "./img/peel.png"},
    {name: "Waxing", description: `Experience the silky smoothness of our professional waxing services at our spa. Our skilled estheticians provide gentle and efficient hair removal, leaving your skin irresistibly soft and hair-free.
    Indulge in our comprehensive waxing menu, offering services for various areas of the body. From brows to legs, underarms to bikini, we've got you covered.
    Using high-quality wax and precise techniques, our estheticians ensure minimal discomfort and exceptional results. Say goodbye to stubble and razors, and say hello to long-lasting smoothness.
    Experience the convenience and confidence of our waxing services. Whether you're looking for a quick touch-up or a full-body transformation, our expert estheticians are here to provide a comfortable and effective hair removal experience.
    Unveil your radiant skin and embrace the freedom of being hair-free. Book your waxing appointment today and discover the ultimate in smoothness and confidence at our spa.`, img: "./img/waxing.png"},
    {name: "Skin Tag Removal", description: "Achieve flawless skin with our expert skin tag removal services. Our professionals use safe techniques to remove skin tags, ensuring minimal discomfort. Say goodbye to bothersome growths and regain your confidence. Experience exceptional care and book your appointment today for smooth, blemish-free skin.", img: "./img/skintag.png"},
    {name: "Lashes", description: "Enhance your natural beauty with our exquisite lash services. From classic extensions to volume lashes, our skilled technicians meticulously apply each lash to create a stunning, customized look. Wake up to effortlessly glamorous lashes that accentuate your eyes. Experience the allure of fuller, longer lashes. Book your appointment today and indulge in the luxury of mesmerizing eyes.", img: "./img/lashes.png"},
    {name: "Teeth whiting", description: "Experience the radiance of a dazzling smile with our professional teeth whitening services. Our expert technicians use safe and effective techniques to brighten your teeth, removing stains and discoloration. Achieve a luminous smile that exudes confidence. Book your appointment today and unlock the power of a brilliant, white smile.", img: "./img/teeth.png"},
    {name: "Intimate bleaching", description: "Discover the beauty of intimate bleaching at our spa. Our specialized treatments gently lighten and even out intimate areas, promoting confidence and enhancing your natural beauty. Experience the ultimate in comfort and discretion with our expert technicians. Book your appointment today and embrace the freedom to feel beautiful from within.", img: "./img/bleaching.png"},
]

const main = document.querySelector("main")

services.forEach((s, i) => {
    const div = document.createElement("div")
    div.innerHTML = `
    <div class="service">
    
    <img src=${s.img} alt=${s.name}>

    <div class="description">
        <h3>${s.name}</h3>
        <p>${s.description}</p>
    
    </div>
    
    </div>
    `

    main.append(div)
})